[package]
name = "rabe_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
bincode = "1.3.3"
rabe = "0.3.1"

[lib]
name = "rabe_lib"
crate-type = ["staticlib"]
